---
- name: install jq and pip3
  become: yes
  apt:
    install_recommends: no
    pkg:
      - jq
      - python3-pip

- name: install yq
  become: yes
  pip: 
    name: yq 
    executable: pip3

- name: Install latest versions of tools from github
  include_role:
    name: gbitdev.get_latest_release_form_github
  loop: "{{ util_repos + repos.split(',') | default([]) }}"
  vars:
    repo: "{{ item }}"
    # selector: "{{ selector }}"

- name: set kubecolor alias
  command: /usr/bin/fish -c 'alias kubectl kubecolor; and funcsave kubectl'
  creates: "~/.config/fish/functions/kubectl.fish"

- name: install kubectl completions
  command: /usr/bin/fish -c 'fisher install evanlucas/fish-kubectl-completions'
  creates: "~/.config/fish/completions/kubectl.fish"