---
- name: install jq
  become: yes
  apt: name=jq state=present

- name: install yq
  become: yes
  pip: name=yq executable=pip3

- name: install kubecolor
  shell: | 
    mkdir -p $HOME/.local/bin && \
    curl -sSL {{ url }} |
    tar xzf - kubecolor && \
    mv kubecolor $HOME/.local/bin/

- name: set kubecolor alias
  command: /usr/bin/fish -c 'alias kubectl kubecolor; and funcsave kubectl'

- name: install kubectl completions
  command: /usr/bin/fish -c 'fisher install evanlucas/fish-kubectl-completions'

- name: set kubectl --export alias
  copy:
    dest: "$HOME/.config/fish/functions/kubectl-export.fish"
    content: |
      function kubectl-export --wraps='kubectl get' --description 'alias of kubectl --export'
        kubectl get $argv -ojson | jq 'del(.metadata.namespace,.metadata.resourceVersion,.metadata.uid) | .metadata.creationTimestamp=null';
      end
